idf_component_register(SRCS "ml_agent.c" "virtual_devices.c" "ml_model.c" "time_sync.c" "display/wifi_setup_screen.c" "wifi_config.c" "face_db.c" "display/setting_screen.c" "enroll_token.c" "mqtt_manager.c" "mqtt_config.c" "display/mqtt_setup_screen.c" "lock.c" "password_manager.c" "app_state.c" "http_server.c" "wifi_manager.c" "button.c" "led.c" "main.c" "display/lcd_driver.c" "display/touch_driver.c" "display/ui_screens.c" "face_recognition.cpp" "i2c_bus.c" "bme280.c" "sensor_task.c" "password_manager.c" "display/keypad_screen.c"
                    INCLUDE_DIRS "." "display"
                    EMBED_TXTFILES "certs/servercert.pem" "certs/prvtkey.pem")